### ISSUE TITLE
java.io.IOException: setDataSourceFD failed

### ISSUE THREAD

**Issue by mobilevisuals** [felixpalmer/android-visualizer#1]
I downloaded the code for "android-visualizer" and I tried to get it to work, but I got the error that I pasted below. What should I to get this to work?

My company is working on an Android visualizer with OpenGL 3d effects and we would like to reuse the code from "android-visualizer" if possible.

---

01-02 10:06:41.282: D/dalvikvm(5376): Late-enabling CheckJNI
01-02 10:06:41.306: I/dalvikvm(5376): Turning on JNI app bug workarounds for target SDK version 9...
01-02 10:06:41.813: E/MediaPlayer(5376): Unable to to create media player
01-02 10:06:41.915: D/MediaPlayer(5376): create failed:
01-02 10:06:41.915: D/MediaPlayer(5376): java.io.IOException: setDataSourceFD failed.: status=0x80000000
01-02 10:06:41.915: D/MediaPlayer(5376):    at android.media.MediaPlayer.setDataSource(Native Method)
01-02 10:06:41.915: D/MediaPlayer(5376):    at android.media.MediaPlayer.create(MediaPlayer.java:740)
01-02 10:06:41.915: D/MediaPlayer(5376):    at com.pheelicks.app.MainActivity.init(MainActivity.java:59)
01-02 10:06:41.915: D/MediaPlayer(5376):    at com.pheelicks.app.MainActivity.onResume(MainActivity.java:39)
01-02 10:06:41.915: D/MediaPlayer(5376):    at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1158)
01-02 10:06:41.915: D/MediaPlayer(5376):    at android.app.Activity.performResume(Activity.java:4539)
01-02 10:06:41.915: D/MediaPlayer(5376):    at android.app.ActivityThread.performResumeActivity(ActivityThread.java:2448)
01-02 10:06:41.915: D/MediaPlayer(5376):    at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:2486)
01-02 10:06:41.915: D/MediaPlayer(5376):    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2000)
01-02 10:06:41.915: D/MediaPlayer(5376):    at android.app.ActivityThread.access$600(ActivityThread.java:128)
01-02 10:06:41.915: D/MediaPlayer(5376):    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1161)
01-02 10:06:41.915: D/MediaPlayer(5376):    at android.os.Handler.dispatchMessage(Handler.java:99)
01-02 10:06:41.915: D/MediaPlayer(5376):    at android.os.Looper.loop(Looper.java:137)
01-02 10:06:41.915: D/MediaPlayer(5376):    at android.app.ActivityThread.main(ActivityThread.java:4514)
01-02 10:06:41.915: D/MediaPlayer(5376):    at java.lang.reflect.Method.invokeNative(Native Method)
01-02 10:06:41.915: D/MediaPlayer(5376):    at java.lang.reflect.Method.invoke(Method.java:511)
01-02 10:06:41.915: D/MediaPlayer(5376):    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:790)
01-02 10:06:41.915: D/MediaPlayer(5376):    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:557)
01-02 10:06:41.915: D/MediaPlayer(5376):    at dalvik.system.NativeStart.main(Native Method)
01-02 10:06:41.915: D/AndroidRuntime(5376): Shutting down VM
01-02 10:06:41.915: W/dalvikvm(5376): threadid=1: thread exiting with uncaught exception (group=0x40bcf1f8)
01-02 10:06:41.915: E/AndroidRuntime(5376): FATAL EXCEPTION: main
01-02 10:06:41.915: E/AndroidRuntime(5376): java.lang.RuntimeException: Unable to resume activity {com.pheelicks.visualizer/com.pheelicks.app.MainActivity}: java.lang.NullPointerException
01-02 10:06:41.915: E/AndroidRuntime(5376):     at android.app.ActivityThread.performResumeActivity(ActivityThread.java:2458)
01-02 10:06:41.915: E/AndroidRuntime(5376):     at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:2486)
01-02 10:06:41.915: E/AndroidRuntime(5376):     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2000)
01-02 10:06:41.915: E/AndroidRuntime(5376):     at android.app.ActivityThread.access$600(ActivityThread.java:128)
01-02 10:06:41.915: E/AndroidRuntime(5376):     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1161)
01-02 10:06:41.915: E/AndroidRuntime(5376):     at android.os.Handler.dispatchMessage(Handler.java:99)
01-02 10:06:41.915: E/AndroidRuntime(5376):     at android.os.Looper.loop(Looper.java:137)
01-02 10:06:41.915: E/AndroidRuntime(5376):     at android.app.ActivityThread.main(ActivityThread.java:4514)
01-02 10:06:41.915: E/AndroidRuntime(5376):     at java.lang.reflect.Method.invokeNative(Native Method)
01-02 10:06:41.915: E/AndroidRuntime(5376):     at java.lang.reflect.Method.invoke(Method.java:511)
01-02 10:06:41.915: E/AndroidRuntime(5376):     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:790)
01-02 10:06:41.915: E/AndroidRuntime(5376):     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:557)
01-02 10:06:41.915: E/AndroidRuntime(5376):     at dalvik.system.NativeStart.main(Native Method)
01-02 10:06:41.915: E/AndroidRuntime(5376): Caused by: java.lang.NullPointerException
01-02 10:06:41.915: E/AndroidRuntime(5376):     at com.pheelicks.app.MainActivity.init(MainActivity.java:60)
01-02 10:06:41.915: E/AndroidRuntime(5376):     at com.pheelicks.app.MainActivity.onResume(MainActivity.java:39)
01-02 10:06:41.915: E/AndroidRuntime(5376):     at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1158)
01-02 10:06:41.915: E/AndroidRuntime(5376):     at android.app.Activity.performResume(Activity.java:4539)
01-02 10:06:41.915: E/AndroidRuntime(5376):     at android.app.ActivityThread.performResumeActivity(ActivityThread.java:2448)
01-02 10:06:41.915: E/AndroidRuntime(5376):     ... 12 more

**Comment by mobilevisuals** [comment]
I got this to work now, by replacing the included mp3 file with "slipaway" by Ultravox. I also had to change this line of code:
MediaPlayer mediaPlayer = MediaPlayer.create(getBaseContext(), R.raw.slipaway);

I think you should replace the included test.mp3 cause it is not working.

**Comment by felixpalmer** [comment]
Happy to include a different file. Could you submit a pull request with your changes please?

**Comment by mobilevisuals** [comment]
Sure, but I haven't used gitbub that much. How do I submit a pull request?

I have started to work on the visualizer with OpenGL 3d effects. I looked at your code and I can now play the music and extract data from it. I have never worked with sound programming before, so I don't know how to proceed further.

I talked to a friend, who is a VJ and the said that there is a single parameter, which describes the music. He said that I could use that parameter to change the speed and the colors of the 3D visuals. Do you know which parameter he means and how it can be calculated?

This is the app, which I plan to add music visualizating to:

https://play.google.com/store/apps/details?id=astral.worldstriall

It is called "Astral 3D worlds" and it contains hypnotic OpenGL 3d effects now. I have a company called "Mobile Visuals". I can mention your project on our website and in the product description for the "Astral 3D worlds" if you want.

**Comment by felixpalmer** [comment]
For help with pull requests, check out: https://help.github.com/articles/using-pull-requests

As for the "single parameter", I'm not sure I follow. For displaying visualizations I use 2 bits of data, the raw waveform and its Fourier transform, see OnDataCaptureListener in VisualizerView.java. These give me the waveform currently being played as well as its frequency composition, respectively. From these you could derive other parameters eg - roughly speaking - the current volume will be related to the maximum amplitude of the waveform or the most prominent peak in the FFT spectrum will tell you about the current pitch of the sound. 

Your app looks pretty neat! I would definitely appreciate a mention.

**Comment by mobilevisuals** [comment]
I tried to follow the instructions to use pull requests, but it seems like I need to have a GitHub repository use pull requests.

Why do you only display FFT data and not the audio data? I have looked at the FFT data in my MP3 file and I can't use it to visualize. They are low values, mostly 0 to 4. The magnitude is usually only 0 to 1.

The AudioData contains much more varied values and it seems possible to use this for visualization.
The magnitude has values like 23533 and 31013.

So the FFT data  is the Fourier transform and the audio data is the raw waveform?

You mentioned the most prominent peak in the FFT spectrum. How do I calculate that? Maybe you already have done that in your project? 

I see that you calculate the magnitude with 

  for (int i = 0; i < data.bytes.length ; i++) {

```
          byte rfk = data.bytes[i];
          byte ifk = data.bytes[ 1];
           magnitude = (rfk * rfk + ifk * ifk);

     }
```

You calculate the magnitude for each value in the loop here and then use them to calculate the posititions of the lines. Do you mean that I should use all of these magnitude values or do you mean the top magntitude for all of the values in the loop? I mean, like this:

 for (int i = 0; i < data.bytes.length ; i++) {

```
          byte rfk = data.bytes[i];
          byte ifk = data.bytes[ 1];
           magnitude = (rfk * rfk + ifk * ifk);

           if(magnitude>maxmagnitude)
           maxmagnitude=magnitude;            
     } 
```

I have writeen about your project in the product description for the full version of Astral 3D worlds on Google play.
You can see this, when it get live on the appstore in a few hours. This is what I wrote:

The code for the music visualizing is inspired by Felix Palmer's open source android-visualizer:

https://github.com/felixpalmer/android-visualizer

**Comment by mobilevisuals** [comment]
How do I calculate the BPM from the music data? I talked to a VJ and he said that this is the most important parameter, for visualizing the music.

**Comment by felixpalmer** [comment]
Yes, to create a pull request you need a github account - but this is free and only takes a second to set up.

Depending on the visualization I use either the FFT or audio data.

For calculating the most prominent peak your code looks fine, except every time you get a new maxmagnitude keep track of what the frequency was. Once you've looped over the entire spectrum, you'll have the most prominent frequency.

There's no simple way of calculating the BPM of a sound file reliably, check out this SO question for some details: http://stackoverflow.com/questions/657073/how-to-detect-bpm-of-the-song-by-programming

**Comment by mobilevisuals** [comment]
I already have an account, but I assume that I should first fork your repo and then create a pull request, so it gets added to your repo? I will try to get this fixed tomorrow.

You wrote "every time you get a new maxmagnitude keep track of what the frequency was". How do I determine the frequency for a certain magnitude?

Thanks for the BPM info, very interesting! Maybe BPM calculation is too complicated and processor intensive for a mobile app? If so, maybe it is better to sync the music with another parameter than BPM? 

I just want to find the easiest and most obvious sound parameter and then sync the speed of the visuals with that.
The next versions of my music visualizer app can be more complicated,but I want to start with the easiest and most obvious sound parameter, to get things right from the beginning.

**Comment by mobilevisuals** [comment]
I tried to follow the instructions to submit a pull request: 

https://help.github.com/articles/creating-a-pull-request

It says that I first have to create a branch in my local repo, commit to it, and push the branch to a repo or fork on GitHub. I can create a branch in my local repo, but I then get the error message "loading commits failed. failed to load commit history for this repository. You might need to open a shell and debug the state of this repo".

You wanted me to submit a pull request with my changes. The only changes that I made was to replace the MP3 file. Maybe we can solve this in an easier way or do you still want me to submit a pull request?

**Comment by felixpalmer** [comment]
As long as you own the rights to the mp3 file - point me at it and I can replace it in the code

**Comment by mobilevisuals** [comment]
I don't own the rights to any MP3 files. I used "slipaway" by Ultravox. It was just a MP3 file that I downloaded some years ago. I picked that file, because it was the first MP3 file that I found on my PC.

Maybe it is better to sync the music with another parameter than BPM, if BPM calculation is too complicated and processor intensive? 

You talked about the most prominent frequency and you wrote "every time you get a new maxmagnitude keep track of what the frequency was". How can the frequency for a certain magnitude be calculated? Would the most prominent frequency be something that I could sync the music with?

**Comment by felixpalmer** [comment]
If you don't own the rights to the file, it's probably best not to commit it to the repository - it's not like it is hard for others to dump in their own mp3 files like you did.

I think you might be right about choosing something different to input into the visualizer rather than the BPM. While the BPM describes a track as a whole, for visualizations I would say it is more effective to use something more real-time to control the visualization. A good example would be the amplitude of the music - if you connected this to a parameter in your visualization (say the brightness) then it should appear that the visualization is 'in time' with the music.

I guess you could use the prominent frequency to control the visualization, although it might be too variable to look good - I guess you'd need to experiment.

To answer your question: to get the frequency in the for loop for the FFT data use the i variable, this is proportional to the frequency. That for loop is looping over FFT data, which is the frequency spectrum - so when i is 0 this corresponds to the lowest frequency and when it is at the end it is the highest frequency. Does that make sense?

**Comment by mobilevisuals** [comment]
I see what you mean, the BPM is usually the same for the whole track. So the visualization would be boring then.

Is the maxmagnitude (which I calculated above in the loop example) the same as the amplitude of the music?

Thanks for the info about the frequency! I will experiment and see if it looks good to use that for the visualization.

**Comment by felixpalmer** [comment]
The max magnitude will be the maximum amplitude of the waveform representing the music. This is a short sample of the track, so the max magnitude will give you a rough idea of how loud the track currently is. However sound perception is quite complex, with our ears being more or less sensitive at different frequencies, so just taking the max amplitude is a rough measure. But just like with the frequency, I think experimenting here is the key - something which might be mathematically correct may look wrong and vice versa - so I wouldn't sweat too much with the details.

For better results, it might make sense to do something a bit more complex, ie calculate the RMS (http://en.wikipedia.org/wiki/Root_mean_square) of the waveform or keep a moving average (http://en.wikipedia.org/wiki/Moving_average) in order to smooth out any kinks

**Comment by mobilevisuals** [comment]
You are right, the RMS magnitude is really useful! I calculate it for the FFT data and it works really good for syncing the brightness and the fog of the 3D-visuals.

That is what I think the RMS magnitude can be best used for. It doesn't look good to sync the speed with it. 
I need something to sync with the speed, since it would be strange if my 3D tunnels and journeys had the same speed for all music. 

The BPM seems to be too complicated and processor intensive to calculate, but maybe it is possible to get a rough estimate on how fast a track is? I mean, not as exact as BPM, just something that indicates that how fast the track is. Do you if this can be determined in an easier and less processor intensive way than BPM?

**Comment by mobilevisuals** [comment]
How do I connect the music visualizer to the common music players like Spotify and Winamp, so I can visualize the music, which comes from these players?

**Comment by felixpalmer** [comment]
I'm not sure it's possible to get at the audio data created by another app - if you find a way please let me know.

**Comment by mobilevisuals** [comment]
There are several apps on Google play, which visualizes music from other players. I have tested BH visualizer, Wire visualizer and Audio glow. They can visualize music from both Spotify and the standard music player on my Samsung Galaxy. You can download these apps for free if you want to see how they work.

**Comment by mobilevisuals** [comment]
I have researched how to get audio data from other apps and it is possible. Here is what the developer of Audio glow visualizer writes:

I need to manually implement each player. A player usually can only be supported if its developer has chosen to broadcast meta data within Android, and I am able to contact them. 

There is more info here:

https://play.google.com/store/apps/details?id=com.cyphercove.audioglowfs&hl=en 

I will not proceed with this in the first version of my visualizing app, I will implement my own player module, which plays MP3 files.

**Comment by swapniladsure** [comment]
Looks like a awesome app..I want to add two color into bar graph render..according to felixpalmer i have made changes but code is not working correctly ..i want two color in one bar or individual color for individual bar in visual.."Mobilevisual" you are expert in this so please help me as i am student i dont have much knowledge of canvas and all stuff..
this is my code
public BarGraphRenderer(int divisions,Paint paint,  boolean top){
 super();
   mDivisions = divisions;
    mPaint = paint;
    mTop = top;
    mpaint2 = new Paint();
    mpaint2.setStrokeWidth(10f);
    mpaint2.setAntiAlias(true);
    mpaint2.setColor(Color.BLUE);
 }
  public void onRender(Canvas canvas, FFTData data, Rect rect) {
    for (int i = 0; i < data.bytes.length / mDivisions; i++) {
      mFFTPoints[i \* 4] = i \* 4 \* mDivisions;
      mFFTPoints[i \* 4 + 2] = i \* 4 \* mDivisions;  
      byte rfk = data.bytes[mDivisions \* i];
      byte ifk = data.bytes[mDivisions \* i + 1];
      float magnitude = (rfk \* rfk + ifk \* ifk);
      int dbValue = (int) (10 \* Math.log10(magnitude)); 
        mFFTPoints[i \* 4 + 1] = rect.height();
        mFFTPoints[i \* 4 + 3] = rect.height() - (dbValue \* 4 - 10);
    }
   canvas.drawLines(mFFTPoints, mPaint);
   for (int i = 0; i < data.bytes.length / mDivisions; i++) {
       canvas.drawLine(mFFTPoints[i \* 4],mFFTPoints[i \* 4 + 1]/2, mFFTPoints[i \* 4 + 2], (mFFTPoints[i \* 4 + 3])/2, mpaint2);

   }

 }

**Comment by mobilevisuals** [comment]
I am trying to find out exactly what the FFT data means. I read the info on 

http://developer.android.com/reference/android/media/audiofx/Visualizer.html#getFft%28byte[]%29

which says "The capture returns the real and imaginary parts of a number of frequency points equal to half of the capture size plus one."

There is no info on which these frequency points are. My capture size is 1024, so there are 1023 frequency points.

The frequency range is from 0 to 22 kHz, since my sampling rate is 44100. This make sense, since these are the frequencies that we normally can hear.

I then read on 
http://stackoverflow.com/questions/4720512/android-2-3-visualizer-trouble-understanding-getfft

that sampled signals don't have any time units (e.g. seconds, Hertz) associated with them.
I assume that this means that the 1023 frequency points don't have any frequency points associated with them. 

How can I then find out how much bass, mid and treble there is?

It would be cool to do a visualization where the red color corresonds to bass sound, the green color corresonds to mid sound and the blue color corresonds to treble sound.

**Comment by swapniladsure** [comment]
@mobilevisuals  yes it would be cool to do visualization according to color correspondence. can you help me to solve my problem.

**Comment by mobilevisuals** [comment]
@swapniladsure It seems like you used BarGraphRenderer from Felix's project and then modified it. I can't say what is wrong with that code, since I don't use that type of visualization in my app. I mean, I don't use BarGraphRenderer. I calculate the RMS (http://en.wikipedia.org/wiki/Root_mean_square) of the waveform and use that for the visualization. The best thing would probably be to start with Felix's project and make sure that is working like it should. Then you can try and modify the code step by step.

I am also trying to find out how to do visualization according to color correspondence, I hope Felix has some info on this.

**Comment by felixpalmer** [comment]
@swapniladsure, please see my comments in the other thread. If you have more questions, please post there rather than adding to this discussion - it makes it clearer for others to follow.

@mobilevisuals, doesn't the linked question give you what you need? I.e. Fk = k \* Fs / N,    k = 0,1,...,N-1

The 1024 data points should be linearly proportional to the frequency spectrum, so roughly speaking the bottom quarter is bass, the 2nd quarter middle and the rest treble.

You shouldn't need to worry about the real and imaginary parts, once you've normalized them as I do, e.g. 

``` Java
float magnitude = (rfk * rfk + ifk * ifk);
```

**Comment by mobilevisuals** [comment]
I see, I calculated the last frequency point according to that formula:

Fk = 1024 \* 44100 / 1023= 44000 Hz

This is twice above what the ear can hear. The info on StackOverFlow says:

"So really all you should worry about for visualization purposes are the FFT output samples corresponding 
to the range of frequencies from 0 to Fs/2."

But you mean that the whole FFT spectrum should be used for visualization? If so, why use the frequencies above 20 000 Hz, which we can't hear?

**Comment by felixpalmer** [comment]
Good point. It's up to you how much of the data you use - if you only want to use the audio in the audible spectrum then just use samples 0-512 (or whatever corresponds to 20kHz)

**Comment by mobilevisuals** [comment]
The magnitude of the signals increases when the volume is turned up. I visualize the magnitude with the brightness or the fog density or fog colors of the visual effects. It gets strange when the visuals become less bright, just because the volume is low. How can I avoid this? Maybe I should normalize the magnitude in some way, so it's not dependent on the volume? I see that you are also using the magnitude in your visualizations. How have you handled this issue?

**Comment by felixpalmer** [comment]
Could you not just get the current volume and compensate accordingly? See http://stackoverflow.com/questions/4593552/android-get-set-media-volume-not-ringtone-volume

This isn't something I've implemented in my project, but I would be happy to add it if you can get it working!
