### ISSUE TITLE
How to change color of every bar in bargraphrender

### ISSUE THREAD

**Issue by swapniladsure** [felixpalmer/android-visualizer#2]
hey guys,
Can anybody please tell me how can i change color of every bar or group of bar into bargraphrender method?
I am new to android i dont know much about canvas and rendering.
please can you help me to change color of each bar in bar visualizer.
like this 
![IMG_0515](https://f.cloud.github.com/assets/2139604/83036/7d70284a-63cb-11e2-8a6f-0bc9338600e3.png)
![visualizer101outofthebox](https://f.cloud.github.com/assets/2139604/83037/8770cb56-63cb-11e2-8b8e-6cbe6deee73a.png)

**Comment by felixpalmer** [comment]
The BarGraphRenderer is initialized with a Paint object - which is used to draw the lines. See [MainActivity](https://github.com/felixpalmer/android-visualizer/blob/master/src/com/pheelicks/app/MainActivity.java) line 93. Play around with these values to change the appearance.

To learn more about Paint objects in Android, check out: http://developer.android.com/reference/android/graphics/Paint.html

**Comment by swapniladsure** [comment]
Yes i can change color by changing color combination.. but it will change the whole colors of bar..i want individual color  set method or group color like 1st 4 coloum having red than next 4 colum having yellow like that..

**Comment by felixpalmer** [comment]
In that case you'll want to write a new Renderer similar to [BarGraphRenderer](https://github.com/felixpalmer/android-visualizer/blob/master/src/com/pheelicks/visualizer/renderer/BarGraphRenderer.java), which uses different Paints for different columns. The for loop in onRender iterates over each bar in turn creating the lines to be drawn. You'll need to modify this to draw each column individually with the Paint you want.

**Comment by swapniladsure** [comment]
Yes something like that but i dont know how can i combine 2 paints object into one canvas ..i was stuck here so i ask you here because i am new to android.. Can you help me to write this small template ?

**Comment by felixpalmer** [comment]
canvas.drawLines(mFFTPoints, mPaint) renders all the lines in mFFTPoints using the Paint mPaint. Just call this function with the points you want to render, along with the paint required. You can make multiple calls to draw on a canvas, the lines will just be drawn on top of what is already there.

**Comment by swapniladsure** [comment]
Thanks i will try according to your suggestion

**Comment by swapniladsure** [comment]
I tried following code to have two color in same bar but it take so much time to render..it is much slower than normal one..
can you help me?

public void onRender(Canvas canvas, FFTData data, Rect rect) {
    for (int i = 0; i < data.bytes.length / mDivisions; i++) {
      mFFTPoints[i \* 4] = i \* 4 \* mDivisions;
      mFFTPoints[i \* 4 + 2] = i \* 4 \* mDivisions;  
      mPaint.setColor(Color.BLUE);
      canvas.drawLines(mFFTPoints, mPaint);
      byte rfk = data.bytes[mDivisions \* i];
      byte ifk = data.bytes[mDivisions \* i + 1];
      float magnitude = (rfk \* rfk + ifk \* ifk);
      int dbValue = (int) (10 \* Math.log10(magnitude)); 
        mFFTPoints[i \* 4 + 1] = rect.height();
        mFFTPoints[i \* 4 + 3] = rect.height() - (dbValue \* 4 - 10);
    }
    mPaint.setColor(Color.GREEN);
   canvas.drawLines(mFFTPoints, mPaint);
 }

**Comment by felixpalmer** [comment]
Your problem is that you're re-drawing all the points every time (not just the ones for that column). In other words when you're drawing column 4 you're also drawing 1, 2 and 3 again. This results in you drawing 0.5*N^2 columns rather than N, hence the drop in speed.

You should clear out the mFFTPoints on every iteration so you don't draw the previous lines needlessly (and perhaps reduce the size of the mFFTPoints array as you no longer need it to hold all the points.

**Comment by swapniladsure** [comment]
Hello,
Somewhat i manage what i want to display. My coding is poor but it display different color for each Bar.
Do you suggest any modification in code to achieve such colorfull bars.
before canvas.drowline i have added for loop to change color of each line.
code :- 
for (int i = 0; i < data.bytes.length / mDivisions; i++) {
        if(i>26)
        {
        mPaint.setColor(Color.BLUE);
        }
        else
        {
        String temp =MyColor[i]; //MyColor is array of string (color string)
        mPaint.setColor(Color.parseColor(temp));
        }
       canvas.drawLine(mFFTPoints[i \* 4],mFFTPoints[i \* 4 + 1], mFFTPoints[i \* 4 + 2], mFFTPoints[i \* 4 + 3], mPaint);
    }

Thank you for help

**Comment by felixpalmer** [comment]
By colorfull, do you mean gradients? If so, check out this SO question on how to set a Shader on the Paint object: http://stackoverflow.com/questions/2836098/how-to-fill-a-path-in-android-with-a-linear-gradient

**Comment by swapniladsure** [comment]
@felixpalmer  You are grate ... this one look awesome on phone.. Thank you so much

**Comment by swapniladsure** [comment]
@felixpalmer Is is possible to fade faster?.. i want to make fading of bar faster.. can you please tell me which code is associated with fading of bar so i can make changes according to that.
I am currently using this 
 mPaint.setShader(new LinearGradient(0, 0, 0,height , Color.WHITE, Color.parseColor("#893786"), Shader.TileMode.MIRROR));
    canvas.drawLines(mFFTPoints, mPaint);

**Comment by felixpalmer** [comment]
The first four parameters to LinearGradient control the position of the gradient, see http://developer.android.com/reference/android/graphics/LinearGradient.html - to make it 'fade faster' try reducing height to height/2

**Comment by swapniladsure** [comment]
@felixpalmer  Not working if i change height/2 than bottom of bar is disappear. when bar goes up than after 3 second it disappear  but i want to disappear it in 1 second. I think this formula can fade that bar faster but i dont know how.
mFFTPoints[i \* 4] = i \* 4 \* mDivisions;
      mFFTPoints[i \* 4 + 2] = i \* 4 \* mDivisions;  
      byte rfk = data.bytes[mDivisions \* i];
      byte ifk = data.bytes[mDivisions \* i + 1];
      float magnitude = (rfk \* rfk + ifk \* ifk);
      int dbValue = (int) (10 \* Math.log10(magnitude)); 
        mFFTPoints[i \* 4 + 1] = rect.height();
        mFFTPoints[i \* 4 + 3] = rect.height() - (dbValue \* 4 - 10);
       float height=mFFTPoints[i \* 4 + 3];

**Comment by felixpalmer** [comment]
Oh I misunderstood, to fade the visualization faster edit the FadePaint in https://github.com/felixpalmer/android-visualizer/blob/master/src/com/pheelicks/visualizer/VisualizerView.java line 68

**Comment by swapniladsure** [comment]
DOne It works fine..Thanks Again

**Comment by swapniladsure** [comment]
@felixpalmer  Hello again. sorry to disturb you can you tell me how can i increase the bar width and how can i join them one to another.. i don't want gap between them.

**Comment by felixpalmer** [comment]
The bars are just a set of lines, with the width defined by the Paint (e.g. paint.setStrokeWidth(50f);) - see MainActivity.java. Increase the width until the bars are the width you need

**Comment by swapniladsure** [comment]
@felixpalmer i am trying to use 2 Bar visualizer , one in portrait and another is in landscape . landscape one is big in size and with color bar. problem is when i shift from portrait to landscape than landscape visualizer not showing bar but if i stop service and start service again than it shows bar on landscape...i think it is problem with Mediaplayer object. when orintation changes media player object is distorted. so i override  retainNonConfigurationInstance method to get player object in landscape mode.. but it throws error "Illegal state exception" on setCaptureSize() called on wrong state" do you know how to solve this problem

**Comment by aldock** [comment]
Hello, i´m implementing a BarGraph with the peak levels with a more  delayed Fade mFadePaint.setColor(Color.argb(248, 255, 255, 255)); within the VisualizerView, however Visualizer only accept one definition for mFadePaint.setColor(Color.argb(248, 255, 255, 255))  and not two different Fades at the same Visualizer Graph. For that I tryied to create a second VisualizerView but, not works simultaneous.  Thank you if anyone can help.

**Comment by aldock** [comment]
Hello, is there a way to avoid visualizer link to Media player lost when changing display orientation ?

**Comment by niteshkhatri** [comment]
Hi, I am using red colors for the bars. I want the bars to fade really fast. If I use below code its not fading faster.

```
    mFadePaint.setColor(Color.argb(238, 255, 255, 255));
```

However, if I replace above code with below code to make it fade faster, the output is it does fades faster but the color is not red anymore its red with too much alpha.

```
    mFadePaint.setColor(Color.argb(100, 255, 255, 255));
```

I want the bars to fade really fast with maintaining their original color. How can I do it?

**Comment by Antipole** [comment]
I want to add line on above the bar graph visualizer and reder line above bar like given image
![visualizer_preview1](https://cloud.githubusercontent.com/assets/10595833/5798453/3daed8cc-9fed-11e4-902c-db51916ddaf9.png)

how can i do it??

**Comment by XNepster** [comment]
@felixpalmer  How could i increase the height of bars. your demo project shows bars with small height. How can I increase the height of it.

**Comment by XNepster** [comment]
How can i remove fade effect in VisualizerView  @swapniladsure ?

**Comment by Dirkstaal** [comment]
hi can any one help i have this code 

Canvas = c;

int H = c.getHeight();

int W = c.getWidth();

int HH = H / 2;

int HW = W / 2;

for (int i = 0; i < 50; i++) { 

    float normalizedInv = (50-i) / 50.0f;

    float n = 1 + normalizedInv \* normalizedInv \* HH;

    c.drawLine((HW + n), (HH + n), (HW - n), (HH + n), p); // bottom: BR to BL

    c.drawLine((HW + n), (HH - n), (HW - n), (HH - n), p); // top: TR - TL

    c.drawLine((HW + n), (HH - n), (HW + n), (HH + n + 1), p); // right: TR - BR, (BTW, what is the "+1" ???)

    c.drawLine((HW - n), (HH - n), (HW - n), (HH + n), p); // left: TL - BL

}

want to fft using 

onRender(Canvas canvas, FftData data, Rect rect)
