### ISSUE TITLE
Magnitude calculation treating unsigned 8-bits incorrectly

### ISSUE THREAD

**Issue by cypherdare** [felixpalmer/android-visualizer#7]
The Visualizer documentation says that the returned bytes in `getFFT()` are unsigned 8-bit numbers. Shouldn't `rfk` and `ifk` be converted to positive Java integers before using them like this, or am I missing something?

```
int rfk = data.bytes[mDivisions * i] & 0xff;
int ifk = data.bytes[mDivisions * i + 1] & 0xff;
```

**Comment by felixpalmer** [comment]
As far as I can see, the [docs](https://developer.android.com/reference/android/media/audiofx/Visualizer.html) only state that the waveform data is unsigned.

```
Waveform data: consecutive 8-bit (unsigned) mono samples by using the getWaveForm(byte[]) method     
Frequency data: 8-bit magnitude FFT by using the getFft(byte[]) method
```

Have you tried to see whether adding the `& 0xff` actually makes a difference? I'm not enough of a Java expert to know if Java does this for us when we convert into a magnitude:

```
float magnitude = (rfk * rfk + ifk * ifk);
```

**Comment by cypherdare** [comment]
It's difficult to test whether the results are truly different, since it's reacting to real-time audio. However, the byte array that's returned does include some negative values in it, and these only appear when there is some magnitude to the sound. 

Good catch--I hadn't noticed that it didn't mention unsigned for the FFT.

**Comment by cypherdare** [comment]
OK, a negative Fourier coefficient makes perfect sense, so I think it's safe to assume that these are signed two's complement bytes coming from the native code, and can safely be squared to compute the magnitude.
